universe = vanilla
Executable = condor_runscript.sh
Output = /afs/desy.de/user/a/anstein/private/aisafety/SF/VHcc-cTagSF/StackPlotter/systStacker_condor/condor_notflat_250_gamma2.0_alphaNone_FGSM/log-$(ClusterId).$(ProcId).out
Error  = /afs/desy.de/user/a/anstein/private/aisafety/SF/VHcc-cTagSF/StackPlotter/systStacker_condor/condor_notflat_250_gamma2.0_alphaNone_FGSM/log-$(ClusterId).$(ProcId).err
Log    = /afs/desy.de/user/a/anstein/private/aisafety/SF/VHcc-cTagSF/StackPlotter/systStacker_condor/condor_notflat_250_gamma2.0_alphaNone_FGSM/log-$(ClusterId).$(ProcId).log
arguments    = $(ClusterId) $(ProcId)
#transfer_input_files = ""
#transfer_output_files = ""
#Should_Transfer_Files = YES
#max_materialize  = 50
#materialize_max_idle = 10

Notification = never
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

queue CMD from cmdList.txt


