universe = vanilla
Executable = condor_runscript.sh
Output = /nfs/dust/cms/user/anstein/ctag_condor/StackPlotter_logs/_multi_adv_tr_eps0.01_5,10,100/log-$(ClusterId).$(ProcId).out
Error  = /nfs/dust/cms/user/anstein/ctag_condor/StackPlotter_logs/_multi_adv_tr_eps0.01_5,10,100/log-$(ClusterId).$(ProcId).err
Log    = /nfs/dust/cms/user/anstein/ctag_condor/StackPlotter_logs/_multi_adv_tr_eps0.01_5,10,100/log-$(ClusterId).$(ProcId).log
arguments    = $(ClusterId) $(ProcId)
#transfer_input_files = ""
#transfer_output_files = ""
#Should_Transfer_Files = YES
#max_materialize  = 50
#materialize_max_idle = 10

Notification = never
on_exit_hold = (ExitBySignal == True) || (ExitCode != 0)

queue CMD from cmdList.txt


